server:
  port: 8888

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/crime-member
    driver-class-name: org.mariadb.jdbc.Driver
    username : root
    password: 1234
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create
      show-sql : true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.connection.provider_disables_autocommit: true