### 유저 등록
POST http://localhost:8888/api/v1/member
Content-Type: application/json

{
  "username" : "seungnyeing",
  "email" : "1234@asd",
  "password1" : "tmdsud258!@",
  "password2" : "tmdsud258!",
  "phone" : "sdsfsdfsdfsdf"
}